index:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    '::index.html.twig'

ndc_blog_bundle:
    resource: "@NDCBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_bundle:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
